name: My Firts Workflow
on: push
jobs:
  firts_job:
    runs-on: ubuntu-latest
    steps:
      -name: Welcome message
      run: echo "My first Github Actions Job"

      -name: List Files
      run: ls

      -name: Read File
      run: cat README.md


